fix: track and display lastAction on player so freeze and slash show instead of claim
rndlabs/monSI pull request #41
Opened 2022-11-03 17:54 UTC by ldeffenb

2022-11-17 08:35 UTC, mfw78 requested changes
Overall looks good, just should use enum for stricter type enforcement.

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +	private lastAction: string | undefined // tracks last action which cannot be derived from blockNumber
I'd most probably suggest that given that the actions are limited and defined, that an enum should be used for this as opposed to a string to more strictly enforce typing.

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'commit'
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		if (this.lastAction) t += ` ${this.lastAction}`
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'reveal'
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'claim'
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'stake'
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'freeze'
Use enum here

2022-11-17 08:35 UTC, mfw78 commented on src/types/entities/player.ts
> +		this.lastAction = 'slash'
Use enum here

2022-11-18 13:28 UTC, ldeffenb commented
While I agree an enum for the phase would be good, can we push this one into develop so that I can get more PRs put together for my other hacks updates?   I'd like to have a good, working, clean, enhanced version ready before RC8 hits mainnet which I'm suspecting will be right around the call next week.

2022-11-18 13:32 UTC, mfw78 commented
No problems pushing it through, just open an issue to do the enum so we don't forget 😊

2022-11-18 13:35 UTC, merged